// Global-stylesheet class names (see app/globals.css), exposed as a plain
// object so page.tsx can reference them the same way it would a CSS Module,
// without splitting the page into per-component module files.
const styles = {
  accentText: "accentText",
  brand: "brand",
  brandIcon: "brandIcon",
  brandWordmark: "brandWordmark",
  btn: "btn",
  btnGhost: "btnGhost",
  btnPrimary: "btnPrimary",
  cmd: "cmd",
  comment: "comment",
  eyebrow: "eyebrow",
  fn: "fn",
  footer: "footer",
  footerBrand: "footerBrand",
  footerInner: "footerInner",
  footerLinks: "footerLinks",
  footerMeta: "footerMeta",
  footerWordmark: "footerWordmark",
  h1: "h1",
  h2: "h2",
  hero: "hero",
  heroActions: "heroActions",
  heroGrid: "heroGrid",
  heroNote: "heroNote",
  installCard: "installCard",
  installCardHead: "installCardHead",
  installCardLabel: "installCardLabel",
  installCode: "installCode",
  installGrid: "installGrid",
  kicker: "kicker",
  kickerDot: "kickerDot",
  kw: "kw",
  lede: "lede",
  nav: "nav",
  navGithub: "navGithub",
  navInner: "navInner",
  navLinks: "navLinks",
  pillar: "pillar",
  pillarBody: "pillarBody",
  pillarIndex: "pillarIndex",
  pillarTitle: "pillarTitle",
  pillars: "pillars",
  problemCol: "problemCol",
  problemGrid: "problemGrid",
  prompt: "prompt",
  section: "section",
  sectionHead: "sectionHead",
  sectionLede: "sectionLede",
  shell: "shell",
  soon: "soon",
  status: "status",
  statusBadge: "statusBadge",
  statusBadgeDot: "statusBadgeDot",
  statusCard: "statusCard",
  statusText: "statusText",
  str: "str",
  terminal: "terminal",
  terminalBar: "terminalBar",
  terminalBody: "terminalBody",
  terminalDot: "terminalDot",
  terminalTitle: "terminalTitle",
  themeDark: "themeDark",
  themeLight: "themeLight",
  tierChip: "tierChip",
  tiers: "tiers",
  tiersLabel: "tiersLabel",
  type: "type",
} as const;

export default styles;
